/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "InterceptModule"
 * 	found in "../lawful-interception.asn1"
 */

#ifndef	_CC_Link_Identifier_H_
#define	_CC_Link_Identifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CC-Link-Identifier */
typedef OCTET_STRING_t	 CC_Link_Identifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CC_Link_Identifier;
asn_struct_free_f CC_Link_Identifier_free;
asn_struct_print_f CC_Link_Identifier_print;
asn_constr_check_f CC_Link_Identifier_constraint;
ber_type_decoder_f CC_Link_Identifier_decode_ber;
der_type_encoder_f CC_Link_Identifier_encode_der;
xer_type_decoder_f CC_Link_Identifier_decode_xer;
xer_type_encoder_f CC_Link_Identifier_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CC_Link_Identifier_H_ */
#include <asn_internal.h>
