/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "InterceptModule"
 * 	found in "../lawful-interception.asn1"
 */

#ifndef	_Direction_Indication_H_
#define	_Direction_Indication_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Direction_Indication {
	Direction_Indication_mono_mode	= 0,
	Direction_Indication_cc_from_target	= 1,
	Direction_Indication_cc_from_other_party	= 2,
	/*
	 * Enumeration is extensible
	 */
	Direction_Indication_direction_unknown	= 3
} e_Direction_Indication;

/* Direction-Indication */
typedef long	 Direction_Indication_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Direction_Indication;
asn_struct_free_f Direction_Indication_free;
asn_struct_print_f Direction_Indication_print;
asn_constr_check_f Direction_Indication_constraint;
ber_type_decoder_f Direction_Indication_decode_ber;
der_type_encoder_f Direction_Indication_encode_der;
xer_type_decoder_f Direction_Indication_decode_xer;
xer_type_encoder_f Direction_Indication_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Direction_Indication_H_ */
#include <asn_internal.h>
