/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "InterceptModule"
 * 	found in "../lawful-interception.asn1"
 */

#ifndef	_LawfulInterceptionData_H_
#define	_LawfulInterceptionData_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>
#include "LawfulInterceptionIdentifier.h"
#include "CommunicationIdentifier.h"
#include "CC-Link-Identifier.h"
#include "Direction-Indication.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Service_Information;

/* LawfulInterceptionData */
typedef struct LawfulInterceptionData {
	OBJECT_IDENTIFIER_t	*domainID	/* OPTIONAL */;
	LawfulInterceptionIdentifier_t	 lawfullInterceptionIdentifier;
	CommunicationIdentifier_t	 communicationIdentifier;
	CC_Link_Identifier_t	*cC_Link_Identifier	/* OPTIONAL */;
	Direction_Indication_t	 direction_Indication;
	OCTET_STRING_t	*bearer_capability	/* OPTIONAL */;
	struct Service_Information	*service_Information	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LawfulInterceptionData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LawfulInterceptionData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Service-Information.h"

#endif	/* _LawfulInterceptionData_H_ */
#include <asn_internal.h>
