/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "InterceptModule"
 * 	found in "../lawful-interception.asn1"
 */

#include "LawfulInterceptionData.h"

static int
memb_domainID_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

static int
memb_bearer_capability_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size >= 1 && size <= 12)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_LawfulInterceptionData_1[] = {
	{ ATF_POINTER, 1, offsetof(struct LawfulInterceptionData, domainID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OBJECT_IDENTIFIER,
		memb_domainID_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"domainID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LawfulInterceptionData, lawfullInterceptionIdentifier),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_LawfulInterceptionIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"lawfullInterceptionIdentifier"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LawfulInterceptionData, communicationIdentifier),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_CommunicationIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"communicationIdentifier"
		},
	{ ATF_POINTER, 1, offsetof(struct LawfulInterceptionData, cC_Link_Identifier),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_CC_Link_Identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cC-Link-Identifier"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LawfulInterceptionData, direction_Indication),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Direction_Indication,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"direction-Indication"
		},
	{ ATF_POINTER, 2, offsetof(struct LawfulInterceptionData, bearer_capability),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		memb_bearer_capability_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bearer-capability"
		},
	{ ATF_POINTER, 1, offsetof(struct LawfulInterceptionData, service_Information),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Service_Information,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"service-Information"
		},
};
static ber_tlv_tag_t asn_DEF_LawfulInterceptionData_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_LawfulInterceptionData_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* domainID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* lawfullInterceptionIdentifier */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* communicationIdentifier */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* cC-Link-Identifier */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* direction-Indication */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* bearer-capability */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 6, 0, 0 } /* service-Information */
};
static asn_SEQUENCE_specifics_t asn_SPC_LawfulInterceptionData_specs_1 = {
	sizeof(struct LawfulInterceptionData),
	offsetof(struct LawfulInterceptionData, _asn_ctx),
	asn_MAP_LawfulInterceptionData_tag2el_1,
	7,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	6,	/* Start extensions */
	8	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_LawfulInterceptionData = {
	"LawfulInterceptionData",
	"LawfulInterceptionData",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_LawfulInterceptionData_tags_1,
	sizeof(asn_DEF_LawfulInterceptionData_tags_1)
		/sizeof(asn_DEF_LawfulInterceptionData_tags_1[0]), /* 1 */
	asn_DEF_LawfulInterceptionData_tags_1,	/* Same as above */
	sizeof(asn_DEF_LawfulInterceptionData_tags_1)
		/sizeof(asn_DEF_LawfulInterceptionData_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_LawfulInterceptionData_1,
	7,	/* Elements count */
	&asn_SPC_LawfulInterceptionData_specs_1	/* Additional specs */
};

