/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "InterceptModule"
 * 	found in "../lawful-interception.asn1"
 */

#include "Service-Information.h"

static int
memb_high_layer_capability_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_tMR_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_bearerServiceCode_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_teleServiceCode_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_Service_Information_1[] = {
	{ ATF_POINTER, 4, offsetof(struct Service_Information, high_layer_capability),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		memb_high_layer_capability_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"high-layer-capability"
		},
	{ ATF_POINTER, 3, offsetof(struct Service_Information, tMR),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		memb_tMR_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"tMR"
		},
	{ ATF_POINTER, 2, offsetof(struct Service_Information, bearerServiceCode),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		memb_bearerServiceCode_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bearerServiceCode"
		},
	{ ATF_POINTER, 1, offsetof(struct Service_Information, teleServiceCode),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		memb_teleServiceCode_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"teleServiceCode"
		},
};
static ber_tlv_tag_t asn_DEF_Service_Information_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_Service_Information_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* high-layer-capability */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* tMR */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* bearerServiceCode */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* teleServiceCode */
};
static uint8_t asn_MAP_Service_Information_mmap_1[(4 + (8 * sizeof(unsigned int)) - 1) / 8] = {
	(0 << 7) | (0 << 6) | (0 << 5) | (0 << 4)
};
static asn_SET_specifics_t asn_SPC_Service_Information_specs_1 = {
	sizeof(struct Service_Information),
	offsetof(struct Service_Information, _asn_ctx),
	offsetof(struct Service_Information, _presence_map),
	asn_MAP_Service_Information_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_Service_Information_tag2el_1,	/* Same as above */
	4,	/* Count of tags in the CXER map */
	0,	/* Whether extensible */
	(unsigned int *)asn_MAP_Service_Information_mmap_1	/* Mandatory elements map */
};
asn_TYPE_descriptor_t asn_DEF_Service_Information = {
	"Service-Information",
	"Service-Information",
	SET_free,
	SET_print,
	SET_constraint,
	SET_decode_ber,
	SET_encode_der,
	SET_decode_xer,
	SET_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Service_Information_tags_1,
	sizeof(asn_DEF_Service_Information_tags_1)
		/sizeof(asn_DEF_Service_Information_tags_1[0]), /* 1 */
	asn_DEF_Service_Information_tags_1,	/* Same as above */
	sizeof(asn_DEF_Service_Information_tags_1)
		/sizeof(asn_DEF_Service_Information_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Service_Information_1,
	4,	/* Elements count */
	&asn_SPC_Service_Information_specs_1	/* Additional specs */
};

